sudo: false

language: node_js

node_js:
  - 5.2.0

addons:
  apt:
    sources:
      - google-chrome
    packages:
    - google-chrome-stable
  firefox: "latest"

before_install:

  - npm install

install:

script:
  - chimp --browser=phantomjs --singleSnippetPerFile=1 --jsonOutput=cucumber/chimpTests.cucumber
