sudo: false

language: node_js

node_js:
  - 5.2.0

addons:
  artifacts: true
    # s3_region: "ap-southeast-2" # defaults to "us-east-1"

# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#     - google-chrome-stable
#   firefox: "latest"

before_install:

    # Use X Virtual Frame Buffer

  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1027x768x16"
  # - sleep 3 # give xvfb some time to start
  # - "export DISPLAY=:99.0"

  - npm install
  - mkdir $HOME/.screenshots

install:

script:
  # - selenium-standalone install --version=2.50.1 --baseURL=https://selenium-release.storage.googleapis.com --basePath=/home/travis/build/Emsiri/chimpjs-tests/node_modules/selenium-standalone/.selenium
  - chimp --browser=phantomjs --singleSnippetPerFile=1 --jsonOutput=chimpTests.json --screenshotsOnError=true --screenshotsPath='$HOME/.screenshots'
